### ISSUE TITLE
Comparison with similar existing boilerplates

### ISSUE THREAD

**Issue by dandv** [beeman/template-typescript-package#153]
Hi @beeman,

Same question as [here](https://github.com/zaki-yama-labs/typescript-npm-package-example/issues/2) - how is this package different from the much more popular https://github.com/bitjson/typescript-starter, or the much more comprehensively documented https://github.com/chriswells0/node-typescript-template? Would help to add that to the README.

**Comment by beeman** [comment]
Hey, I have just forked an existing project for personal use and made some changes.

I'm have little interest in adding a comparison in the Readme as the goal is not to compete/be compared to other projects, it served purely a personal purpose.

These days though I create most of my packages in an Nx Workspace, I have not used this template for weeks if not months.
